### ISSUE TITLE
Upsidedown Android Thumbnail Orientation

### ISSUE THREAD

**Issue by marcejohnson** [mybigday/react-native-media-meta#2]
The Android code isn't respecting the rotation metadata that gets stored inside the video when recording video using Android's standard camera classes for recording.  

Therefore thumbnails are upside down for some videos.

Here is sample code to resolve this:
https://software.intel.com/en-us/forums/intel-media-sdk/topic/561046#comment-1840836
(with full discussion of the issue and sample test videos as well).

Do you have a fix in the works for this, or should I create a pull request?

Thanks and please advise.

**Comment by ranjitpandit** [comment]
I'm still seeing this issue. @marcejohnson were you able to resolve this?

**Comment by ranjitpandit** [comment]
fixed it here.
https://github.com/ranjitpandit/react-native-media-meta/commits/master

**Comment by ranjitpandit** [comment]
Here is the PR

https://github.com/mybigday/react-native-media-meta/pull/4
