### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by surenderkhowal** [mybigday/react-native-media-meta#21]
Cannot read property 'get' of undefined

**Comment by CasanaT** [comment]
You need to rebuild the project after you linked a new library.  And probably clean it before.

**Comment by isohanvanani** [comment]
I resolved by creating .podspec file in node modules and then installed pods.

RNMediaMeta.podspec
```

package = JSON.parse(File.read(File.join(__dir__, "package.json")))
version = package['version']

Pod::Spec.new do |s|
  s.name             = "RNMediaMeta"
  s.version          = version
  s.summary          = package["description"]
  s.requires_arc = true
  s.license      = 'MIT'
  s.homepage     = 'n/a'
  s.authors      = { "ivpusic" => "" }
  s.source       = { :git => "https://github.com/mybigday/react-native-media-meta", :tag => 'v#{version}'}
  s.source_files = 'ios/RNMediaMeta/*.{h,m}'
  s.platform     = :ios, "8.0"
  s.dependency 'React-Core'
end

```


File Location: node_modules/react-native-media-meta/

**Comment by matthewadel** [comment]
> I resolved by creating .podspec file in node modules and then installed pods.
> 
> RNMediaMeta.podspec
> 
> ```
> 
> package = JSON.parse(File.read(File.join(__dir__, "package.json")))
> version = package['version']
> 
> Pod::Spec.new do |s|
>   s.name             = "RNMediaMeta"
>   s.version          = version
>   s.summary          = package["description"]
>   s.requires_arc = true
>   s.license      = 'MIT'
>   s.homepage     = 'n/a'
>   s.authors      = { "ivpusic" => "" }
>   s.source       = { :git => "https://github.com/mybigday/react-native-media-meta", :tag => 'v#{version}'}
>   s.source_files = 'ios/RNMediaMeta/*.{h,m}'
>   s.platform     = :ios, "8.0"
>   s.dependency 'React-Core'
> end
> ```
> 
> File Location: node_modules/react-native-media-meta/

the solution is right except the file is called react-native-media-meta.podspec instead of  RNMediaMeta.podspec and in the file replace  s.name             = "RNMediaMeta" width  s.name             = "react-native-media-meta"

**Comment by sir-george2500** [comment]
I have the same problem 

### **```
null is not an I have the same problem 

```**
null is not an object (evaluating 'RNMediaMeta.get')
at node_modules\react-native-media-meta\index.js:null 
in default.get
```

react-native version 0.71.0

as anyone resolved it I already try the method of creating a podspec object (evaluating 'RNMediaMeta.get')
at node_modules\react-native-media-meta\index.js:null 
in default.get
```

react-native version 0.71.0

as anyone resolved it I already try the method of creating a podspec file however that didn't work
