### ISSUE TITLE
Can we get this with help of `yarn`?

### ISSUE THREAD

**Issue by fatinWasta** [mybigday/react-native-media-meta#26]
I getting error while installing with yarn, just cross confirming if this package is available with yarn? 
<img width="716" alt="Screenshot 2020-07-29 at 12 17 13 PM" src="https://user-images.githubusercontent.com/14032221/88766425-a235f980-d195-11ea-8f43-89d18fdac0a4.png">

RN newbie
Thanks

**Comment by JoshWalshaw** [comment]
You need to use `yarn add react-native-media-meta`
