### ISSUE TITLE
Hangs when installing APK

### ISSUE THREAD

**Issue by juddey** [mybigday/react-native-media-meta#3]
This install was working, until about a day ago, when I got:
```
~/projects/react-native/app$ react-native run-android
Scanning 797 folders for symlinks in /home/justin/projects/react-native/app/node_modules (6ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Reading env from: .env
> Configuring > 3/15 projects > Resolving dependencies ':app:_debugApk' > Resolving dependencies ':react-native-media-meta:_debugPublish
```
... it just hangs with a blank cursor in the terminal.

**Comment by emuen** [comment]
I have the same error. When I run-android, I get:

> Building and installing the app on the device (cd android && ./gradlew installDebug...
> Configuring > 5/11 projects > Resolving dependencies ':react-native-media-meta:_debugCompile'

**Comment by JBerendes** [comment]
close as it has been resolved.

**Comment by deepak-nagdoo** [comment]
i have a same issue but there is no folder named react-native-media-meta .. what should i does to resolve it
